### ISSUE TITLE
Cannot start game locally

### ISSUE THREAD

**Issue by juanvictorleite** [Zomis/minesweeper-flags-client#56]
Hey! Just tried running locally, logged in as a guest. But when I try to start a game, I get this error:

```
gameTools.js:33 Uncaught TypeError: core.Game is not a constructor
    at Object.createGame (gameTools.js:33:1)
    at Store.newGame (gamesStore.js:123:1)
    at wrappedMutationHandler (vuex.esm.js:722:13)
    at commitIterator (vuex.esm.js:390:7)
    at Array.forEach (<anonymous>)
    at eval (vuex.esm.js:389:11)
    at Store._withCommit (vuex.esm.js:520:3)
    at Store.commit (vuex.esm.js:388:8)
    at Store.boundCommit [as commit] (vuex.esm.js:333:19)
    at local.commit (vuex.esm.js:676:13)
```

I think maybe the `minesweeper-core.js` file we get from the Readme is a different version than what the client code expects.

@Zomis Could you check that?

**Comment by Zomis** [comment]
Hi! Thank you for your interest in the project!

I have to admit I don't know why it wasn't matching correctly, but I have updated the `minesweeper-core.js` file now and it should work if you replace your file with the new one (also make sure that you don't get a cached version).

Can you check if it works for you with the new file?
